// Character shader
// Includes falloff shadow and highlight, specular, reflection, and normal mapping

// Material parameters
float4 _Color;
float4 _ShadowColor;
float4 _LightColor0;
float _SpecularPower;
float4 _MainTex_ST;

// Textures
sampler2D _MainTex;
sampler2D _FalloffSampler;
sampler2D _RimLightSampler;
sampler2D _SpecularReflectionSampler;
sampler2D _EnvMapSampler;
sampler2D _NormalMapSampler;

half _Pos;
half _App;

// Constants
#define FALLOFF_POWER 0.3

#ifdef ENABLE_CAST_SHADOWS

// Structure from vertex shader to fragment shader
struct v2f
{
	float4 pos      : SV_POSITION;
	LIGHTING_COORDS( 0, 1 )
	float2 uv       : TEXCOORD2;
	float3 eyeDir   : TEXCOORD3;
	float3 lightDir : TEXCOORD4;
	float3 normal   : TEXCOORD5;
	float4 wpos : TEXCOORD6;
	float4 spos : TEXCOORD7;
#ifdef ENABLE_NORMAL_MAP
	float3 tangent  : TEXCOORD8;
	float3 binormal : TEXCOORD9;
#endif
};

#else

// Structure from vertex shader to fragment shader
struct v2f
{
	float4 pos      : SV_POSITION;
	float2 uv       : TEXCOORD0;
	float3 eyeDir   : TEXCOORD1;
	float3 lightDir : TEXCOORD2;
	float3 normal   : TEXCOORD3;
	float4 wpos : TEXCOORD4;
	float4 spos : TEXCOORD5;
#ifdef ENABLE_NORMAL_MAP
	float3 tangent  : TEXCOORD6;
	float3 binormal : TEXCOORD7;
#endif
};

#endif

// Float types
#define float_t    half
#define float2_t   half2
#define float3_t   half3
#define float4_t   half4
#define float3x3_t half3x3

// Vertex shader
v2f vert( appdata_tan v )
{
	v2f o;
	o.pos = o.spos = UnityObjectToClipPos( v.vertex );
	o.wpos = mul(unity_ObjectToWorld, v.vertex);
	o.uv.xy = TRANSFORM_TEX( v.texcoord.xy, _MainTex );
	o.normal = normalize( mul( unity_ObjectToWorld, float4_t( v.normal, 0 ) ).xyz );

	// Eye direction vector
	half4 worldPos = mul( unity_ObjectToWorld, v.vertex );
	o.eyeDir.xyz = normalize( _WorldSpaceCameraPos.xyz - worldPos.xyz ).xyz;
	o.lightDir = WorldSpaceLightDir( v.vertex );

#ifdef ENABLE_NORMAL_MAP
	// Binormal and tangent (for normal map)
	o.tangent = normalize( mul( unity_ObjectToWorld, float4_t( v.tangent.xyz, 0 ) ).xyz );
	o.binormal = normalize( cross( o.normal, o.tangent ) * v.tangent.w );
#endif

#ifdef ENABLE_CAST_SHADOWS
	TRANSFER_VERTEX_TO_FRAGMENT( o );
#endif

	return o;
}

// Overlay blend
inline float3_t GetOverlayColor( float3_t inUpper, float3_t inLower )
{
	float3_t oneMinusLower = float3_t( 1.0, 1.0, 1.0 ) - inLower;
	float3_t valUnit = 2.0 * oneMinusLower;
	float3_t minValue = 2.0 * inLower - float3_t( 1.0, 1.0, 1.0 );
	float3_t greaterResult = inUpper * valUnit + minValue;

	float3_t lowerResult = 2.0 * inLower * inUpper;

	half3 lerpVals = round(inLower);
	return lerp(lowerResult, greaterResult, lerpVals);
}

#ifdef ENABLE_NORMAL_MAP

// Compute normal from normal map
inline float3_t GetNormalFromMap( v2f input )
{
	float3_t normalVec = normalize( tex2D( _NormalMapSampler, input.uv ).xyz * 2.0 - 1.0 );
	float3x3_t localToWorldTranspose = float3x3_t(
		input.tangent,
		input.binormal,
		input.normal
	);

	normalVec = normalize( mul( normalVec, localToWorldTranspose ) );
	return normalVec;
}

#endif

float  modc(float  a, float  b) { return a - b * floor(a/b); }
float2 modc(float2 a, float2 b) { return a - b * floor(a/b); }
float3 modc(float3 a, float3 b) { return a - b * floor(a/b); }
float4 modc(float4 a, float4 b) { return a - b * floor(a/b); }

float2 boxcell(float3 p3, float3 n)
{
	float2 p;
	float t = 0.7;
	if(abs(n.x)>t) {
		p = p3.yz;
	}
	else if(abs(n.z)>t) {
		p = p3.xy;
	}
	else {
		p = p3.xz;
	}

	p = frac(p);
	float r = 0.123;
	float v = 0.0, g = 0.0;
	r = frac(r * 9184.928);
	float cp, d;
		
	d = p.x;
	g += pow(clamp(1.0 - abs(d), 0.0, 1.0), 1000.0);
	d = p.y;
	g += pow(clamp(1.0 - abs(d), 0.0, 1.0), 1000.0);
	d = p.x - 1.0;
	g += pow(clamp(3.0 - abs(d), 0.0, 1.0), 1000.0);
	d = p.y - 1.0;
	g += pow(clamp(1.0 - abs(d), 0.0, 1.0), 10000.0);
		
		
	const int iter = 11;
	for(int i = 0; i < iter; i ++)
	{
		cp = 0.5 + (r - 0.5) * 0.9;
		d = p.x - cp;
		//g += pow(clamp(1.0 - abs(d), 0.0, 1.0), 200.0);
		g += clamp(1.0 - abs(d), 0.0, 1.0) > 0.995-(0.00075*i) ? 1.0 : 0.0;
		if(d > 0.0) {
			r = frac(r * 4829.013);
			p.x = (p.x - cp) / (1.0 - cp);
			v += 1.0;
		}
		else {
			r = frac(r * 1239.528);
			p.x = p.x / cp;
		}
		p = p.yx;
	}
	v /= float(iter);
	return float2(g, v);
}
// Fragment shader
float4 frag( v2f i ) : COLOR
{
	//if(dot(i.eyeDir, i.normal)<0.0) { discard; }

	float4_t diffSamplerColor = tex2D( _MainTex, i.uv.xy );

#ifdef ENABLE_NORMAL_MAP
	float3_t normalVec = GetNormalFromMap( i );
#else
	float3_t normalVec = i.normal;
#endif

	// Falloff. Convert the angle between the normal and the camera direction into a lookup for the gradient
	float_t normalDotEye = dot( normalVec, i.eyeDir.xyz );
	float_t falloffU = clamp( 1.0 - abs( normalDotEye ), 0.02, 0.98 );
	float4_t falloffSamplerColor = FALLOFF_POWER * tex2D( _FalloffSampler, float2( falloffU, 0.25f ) );
	float3_t shadowColor = diffSamplerColor.rgb * diffSamplerColor.rgb;
	float3_t combinedColor = lerp( diffSamplerColor.rgb, shadowColor, falloffSamplerColor.r );
	combinedColor *= ( 1.0 + falloffSamplerColor.rgb * falloffSamplerColor.a );

	// Specular
	// Use the eye vector as the light vector
#ifdef ENABLE_SPECULAR
	float4_t reflectionMaskColor = tex2D( _SpecularReflectionSampler, i.uv.xy );
	float_t specularDot = dot( normalVec, i.eyeDir.xyz );
	float4_t lighting = lit( normalDotEye, specularDot, _SpecularPower );
	float3_t specularColor = saturate( lighting.z ) * reflectionMaskColor.rgb * diffSamplerColor.rgb;
	combinedColor += specularColor;
#endif

	// Reflection
#ifdef ENABLE_REFLECTION
	float3_t reflectVector = reflect( -i.eyeDir.xyz, normalVec ).xzy;
	float2_t sphereMapCoords = 0.5 * ( float2_t( 1.0, 1.0 ) + reflectVector.xy );
	float3_t reflectColor = tex2D( _EnvMapSampler, sphereMapCoords ).rgb;
	reflectColor = GetOverlayColor( reflectColor, combinedColor );

	combinedColor = lerp( combinedColor, reflectColor, reflectionMaskColor.a );
#endif
	combinedColor *= _Color.rgb * _LightColor0.rgb;
	float opacity = diffSamplerColor.a * _Color.a * _LightColor0.a;

#ifdef ENABLE_CAST_SHADOWS
	// Cast shadows
	shadowColor = _ShadowColor.rgb * combinedColor;
	float_t attenuation = saturate( 2.0 * LIGHT_ATTENUATION( i ) - 1.0 );
	combinedColor = lerp( shadowColor, combinedColor, attenuation );
#endif

	// Rimlight
#ifdef ENABLE_RIMLIGHT
	float_t rimlightDot = saturate( 0.5 * ( dot( normalVec, i.lightDir ) + 1.0 ) );
	falloffU = saturate( rimlightDot * falloffU );
	falloffU = tex2D( _RimLightSampler, float2( falloffU, 0.25f ) ).r;
	float3_t lightColor = diffSamplerColor.rgb; // * 2.0;
	combinedColor += falloffU * lightColor;
#endif

if(_App == 1){
	float2 dg = boxcell(i.wpos, i.normal);
	float fade = i.wpos.y+1.0 - _Time.y+dg.y*0.5;
	//if(fade>0.0) { discard; }
		if (_Pos< i.wpos.y ) {
			discard;
		}
	float s = max((0.8-modc(i.wpos.y + _Time.y*1.0 + 1.5, 3.33)), 0.0) * 10.0;
	float pc = 1.0-clamp(1.0 - max(min(dg.x, 2.0)-1.0, 0.0)*2.0, 0.0, 1.0);
	i.spos /= i.spos.w;
	float scanline = max(min(abs(modc(i.spos.y, 0.02)-0.01)*100.0, 1.0), 0.5);
	float na = 1.0 - abs(dot(i.normal, i.eyeDir.xyz));
	combinedColor *= float3(0.3, 0.3, 0.6) * 1.5 * (modc(_Time.y, 0.0073)*1.0+1.0) * (pc*s*na+1.0);
	combinedColor *= scanline;
	//if(fade>-0.15) { combinedColor.rgb *= 5.0; }
	}

	return float4( combinedColor, opacity);
}
